### ISSUE TITLE
Scanner timeout

### ISSUE THREAD

**Issue by quukske77** [aquasecurity/trivy#2454]
When scanning  image rancher/rancher-agent:v2.6.5 with version 0.28.1 everything works ok.
![image](https://user-images.githubusercontent.com/106823500/177185438-708d52a2-15f4-49a1-9925-84af3b0f4f1c.png)

When scanning the same image with version 0.29.0, 0.29.1 or 0.29.2 i will get a timeout.
![image](https://user-images.githubusercontent.com/106823500/177185835-49e4b7d7-c369-4a26-9194-c1a298515400.png)

Even with timeout 60 minutes and with -security-checks vuln

**Comment by ralfstuckert** [comment]
Experiencing similar problem here for 0.29.1 and 0.29.2 called via [trivy-action ](https://github.com/aquasecurity/trivy-action)
`FATAL	image scan error: scan error: image scan failed: failed analysis: analyze error: timeout: context deadline exceeded`

Worked with 0.29.0 ([trivy action 0.4.1](https://github.com/aquasecurity/trivy-action/blob/0.4.1/Dockerfile)).

Parameters
`--format  sarif --exit-code  1 --ignore-unfixed --vuln-type  os --security-checks  vuln --severity  CRITICAL,HIGH --output  trivy-results.sarif --timeout  30m --no-progress`

**Comment by DmitriyLewen** [comment]
Hello @ralfstuckert @quukske77 
thanks for your reports!

We fixed this bug.
Fix will be include to [next release](https://github.com/aquasecurity/trivy/milestone/7)

Best Regards, Dmitriy

**Comment by ralfstuckert** [comment]
I still experience the same problem as described [above](https://github.com/aquasecurity/trivy/issues/2454#issuecomment-1174734695) in version 30.2 ([trivy action 0.0.6](https://github.com/aquasecurity/trivy-action/releases/tag/0.6.0)).

Shall I open a new issue?

**Comment by DmitriyLewen** [comment]
Hello @ralfstuckert 
I reopen this issue.

Can you post your `debug` log to investigate your issue?
Also can you tell which image you are scanning?

**Comment by ralfstuckert** [comment]
The images having this problem contain quite large java applications based on jHipster, which introduces dependencies to ALL existing java libraries, no kidding :-|

I will try to generate debug log

**Comment by ralfstuckert** [comment]
[debug.txt](https://github.com/aquasecurity/trivy/files/9187404/debug.txt)

**Comment by DmitriyLewen** [comment]
looks like the 5 minute timeout is small for large images.
does scan with large timeout have the same logs?

**Comment by ralfstuckert** [comment]
I use a 30 Min timeout. 

Since I had to use the yaml config in order switch debug on, the timeout parameter seems not have been used in this run :-/

**Comment by DmitriyLewen** [comment]
can you use big timeout please(you can [set](https://aquasecurity.github.io/trivy/v0.30.3/docs/references/customization/config-file/#global-options) this in config file) and scan again.

**Comment by ralfstuckert** [comment]
If providing all parameters via config file, the timeout works correctly (the scan takes about 15 minutes), so I guess the problem is not on your side, but maybe in the calling action. Investigating further

**Comment by DmitriyLewen** [comment]
so Trivy works correctly - I'm closing the issue.

If you have any questions or problems, feel free to open new issue.

Best regards, Dmitriy
